### ISSUE TITLE
Dist::Zilla::Plugin::Substitute fail tests with Role::Tiny-1.3.2

### ISSUE THREAD

**Issue by powerman** [rjbs/Throwable#14]
Yeah, I know, subject doesn't sounds like related to Throwable, sorry, but I've no experience with Moose, and have no idea how to debug this issue. And, honestly, I'm pretty sure this debugging issue is problem with Moose, not with me. So: Dist::Zilla::Plugin::Substitute tests fail with this message:
```
t/basic.t ............... You can only consume roles, Throwable is not a Moose role at /usr/lib64/perl5/vendor_perl/5.20.2/x86_64-linux/Moose/Util.pm line 138.
```
This issue is solved by upgrading Role::Tiny from 1.3.2 to 1.3.4. I've no idea which module's dependency should be fixed - D::Z::P::Substitute (unlikely, see Leont/dist-zilla-plugin-substitute#4), this module, or someone else - hope you'll help me find this out.

**Comment by oalders** [comment]
@haarg any ideas?

**Comment by haarg** [comment]
@powerman, what version of Moo do you have installed?

**Comment by powerman** [comment]
1.007

**Comment by haarg** [comment]
@powerman Moo 1.007 already requires Role::Tiny 1.003004.  I wasn't able to reproduce this issue with the last version of Moo that supports Role::Tiny 1.003002.  It seems like your installed modules got in a bad state.

**Comment by powerman** [comment]
@haarg You probably right. I've used to install all perl modules using Gentoo package manager, and I've just checked package for Moo-1.7.0 - it does depend on Role::Tiny but without mentioning minimal version - so looks like that package is incorrect and result in this issue. I've already discussed this issue with Gentoo devs and switched to installing perl modules using cpanm as root instead of using package manager - looks like this is officially recommended way for perl development in Gentoo now.

**Comment by rjbs** [comment]
so… is there any action for me to take here?

**Comment by haarg** [comment]
No.  The metadata of Throwable and Moo are fine.

**Comment by powerman** [comment]
Sorry to wasting your time and thanks for your help!

**Comment by rjbs** [comment]
My time is here to be wasted by fellow programmers!  Happy hacking! :)
