### ISSUE TITLE
Consider splitting into two or three separate distributions

### ISSUE THREAD

**Issue by dagolden** [rjbs/Throwable#17]
I'd like to be able to depend on Throwable without also depending on Devel::StackTrace, which I don't use.

Perhaps Throwable::Error and StackTrace::Auto should go into their own distributions?  (Or into a single one with both.)

**Comment by rjbs** [comment]
I think the only change in prereqs would be dropping Module::Runtime.  I realize it's absurdly much late to make any reply at all, but:  I plan to keep this as it is.
