### ISSUE TITLE
Code smell in contructor?

### ISSUE THREAD

**Issue by robrwo** [rjbs/Throwable#21]
The code:
```perl
sub throw {
  my ($inv) = shift;
```
looks like a code smell. Shouldn't you be using
```perl
sub throw P
  my $inv = shift;
```

**Comment by rjbs** [comment]
You don't provide any reasoning for this.  No, it's fine.  I guess you don't like that there are parentheses when they're not needed, but they don't cause a problem.

**Comment by robrwo** [comment]
My reasoning is that `shift` doesn't return a list. It lends itself to someone changing it in the future to
```perl
sub throw {
  my ($inv, $arg) = shift;
```
Tests that rely on the change would probably fail in the future.
